export const RU_TEXT = {
  welcomeTitle:'Уважаемые ценители кода!',
  welcomeText:`Приветствуем вас в нашем приложении.
  Мы - команда энтузиастов, которые забросили оливье и мандарины, оставили родных веселиться под ёлкой и с головой погрузились в увлекательный мир React! 
  И вот - наш финальный проект перед вами.`,
  welcomeText2:'Для начала работы необходимо авторизоваться ',
  welcomeText3:'Приятного времяпрепровождения!',
  login: 'Авторизоваться',
  email: 'Email:',
  password: 'Пароль:',
  newUser: 'У вас нет учетной записи? ',
  newUserLink: 'Зарегистрируйтесь здесь.',
  logOut: 'Выйти',
  registration: 'Зарегистрироваться',
  username: 'Имя пользователя',
  confirmPassword: 'Подтвердите пароль: ',
  loginHere: 'Войти здесь',
  haveAccount: 'У вас уже есть учетная запись? ',
  connectAPI: 'Подключиться к апи',
  variables: 'Переменные',
  headers: 'HTTP Заголовки',
  response: 'Запрос',
  toMain: 'На главную',
  schema: 'схему',
  openSchema: 'открыть',
  closeSchema: 'закрыть',
  apiError: 'Ошибка! Такого апи не существует или он недоступен.',
  syntaxError: 'Невалидный формат JSON',
  developer1:'Мардон',
  developer2:'Роман',
  developer3:'Ольга',

};

export const EN_TEXT = {
  welcomeTitle:'Dear code lovers!',
  welcomeText:`Welcome to our application! 
  We are a team of enthusiasts who put aside the stuffed turkey and gingerbread, left our loved ones to have fun under the tree and plunged into the exciting world of React.
  And here is our final project in front of you.`,
  welcomeText2:'To get started, you need to log in ',
  welcomeText3:'Enjoy your time!',   
  login: 'Login',
  email: 'Email:',
  password: 'Password:',
  newUser: 'Don&apos;t have an account? ',
  newUserLink: 'Register here',
  logOut: 'Log out',
  registration: 'Registration',
  username: 'Username',
  confirmPassword: 'Confirm Password: ',
  loginHere: 'Login here',
  haveAccount: 'Already have an account?',
  connectAPI: 'Connect to api',
  variables: 'Variables',
  headers: 'HTTP Headers',
  response: 'Response',
  toMain: 'To main',
  schema: 'schema',
  openSchema: 'open',
  closeSchema: 'close',
  apiError: 'Error! No such API exists or is not available',
  syntaxError: 'Invalid JSON format',
  developer1:'Mardon',
  developer2:'Roman',
  developer3:'Olga',
};

export const FR_TEXT = {
  welcomeTitle:'Chers amateurs de code!',
  welcomeText:`Bienvenue sur notre application! 
  Nous sommes une équipe de passionnés qui ont laissé de côté les huîtres et la bûche de Noël, laissant leurs proches s'amuser sous le sapin, et plongés à corps perdu dans l'univers passionnant de React!
  Et maintenant, notre projet final est devant vous.`,
  welcomeText2:'Tout d’abord, vous devez vous authentifier ',
  welcomeText3:'Profitez de votre temps!',  
  login: 'Se connecter',
  email: 'Email:',
  password: 'Mot de passe:',
  newUser: "Vous n'avez pas de compte? ",
  newUserLink: 'Inscrivez-vous ici',
  logOut: 'Déconnexion',
  registration: 'Inscription',
  username: 'Username',
  confirmPassword: 'Confirmer le mot de passe:',
  loginHere: 'Connectez-vous ici',
  haveAccount: 'Vous avez déjà un compte? ',
  connectAPI: 'Connectez-vous à l’API',
  variables: 'variables',
  headers: 'En-têtes HTTP',
  response: 'réponse',
  toMain: 'au principal',
  schema: 'schéma',
  openSchema: 'ouvrir',
  closeSchema: 'fermer',
  apiError: "Erreur! Aucune API de ce type n'existe ou n'est pas disponible.",
  syntaxError: 'Format JSON invalide',
  developer1:'Mardon',
  developer2:'Roman',
  developer3:'Olga',
};
