export const RU_TEXT = {
  welcomeText: 'Добро пожаловать',
  login: 'Авторизоваться',
  email: 'Email:',
  password: 'Пароль:',
  newUser: 'У вас нет учетной записи? ',
  newUserLink: 'Зарегистрируйтесь здесь.',
  logOut: 'Выйти',
  registration: 'Регистрация',
  username: 'Имя пользователя',
  confirmPassword: 'Подтвердите пароль: ',
  loginHere: 'Войти здесь:',
  haveAccount: 'У вас уже есть учетная запись',
  connectAPI: 'Подключиться к апи',
  variables: 'Переменные',
  headers: 'HTTP Заголовки',
  response: 'Запрос',
  toMain: 'На главную',
  schema: 'схему',
  openSchema: 'открыть',
  closeSchema: 'закрыть',
  apiError: 'Ошибка! Такого апи не существует или он недоступен.',
  syntaxError: 'Невалидный формат JSON'
};

export const EN_TEXT = {
  welcomeText: 'Welcome',
  login: 'Login',
  email: 'Email:',
  password: 'Password:',
  newUser: 'Don&apos;t have an account? ',
  newUserLink: 'Register here',
  logOut: 'Log out',
  registration: 'Registration',
  username: 'Username',
  confirmPassword: 'Confirm Password: ',
  loginHere: 'Login here:',
  haveAccount: 'Already have an account?',
  connectAPI: 'Connect to api',
  variables: 'Variables',
  headers: 'HTTP Headers',
  response: 'Response',
  toMain: 'To main',
  schema: 'schema',
  openSchema: 'open',
  closeSchema: 'close',
  apiError: 'Error! No such API exists or is not available',
  syntaxError: 'Invalid JSON format',
};

export const FR_TEXT = {
  welcomeText: 'Bienvenue',
  login: 'Se connecter',
  email: 'Email:',
  password: 'Mot de passe:',
  newUser: "Vous n'avez pas de compte? ",
  newUserLink: 'Inscrivez-vous ici',
  logOut: 'Déconnexion',
  registration: 'Inscription',
  username: 'Username',
  confirmPassword: 'Confirmer le mot de passe:',
  loginHere: 'Connectez-vous ici:',
  haveAccount: 'Vous avez déjà un compte?',
  connectAPI: 'Connectez-vous à l’API',
  variables: 'variables',
  headers: 'En-têtes HTTP',
  response: 'réponse',
  toMain: 'au principal',
  schema: 'schéma',
  openSchema: 'ouvrir',
  closeSchema: 'fermer',
  apiError: "Erreur! Aucune API de ce type n'existe ou n'est pas disponible.",
  syntaxError: 'Format JSON invalide',
};
