export const RU_TEXT = {
  welcomeTitle: 'Уважаемые ценители кода!',
  welcomeText: `Приветствуем вас в нашем приложении.
  Мы - команда энтузиастов, которые забросили оливье и мандарины, оставили родных веселиться под ёлкой и с головой погрузились в увлекательный мир React! 
  И вот - наш финальный проект перед вами.`,
  welcomeText2: 'Для начала работы необходимо авторизоваться ',
  welcomeText3: 'Приятного времяпрепровождения!',
  login: 'Авторизоваться',
  email: 'Email:',
  password: 'Пароль:',
  newUser: 'У вас нет учетной записи? ',
  newUserLink: 'Зарегистрируйтесь здесь',
  logOut: 'Выйти',
  registration: 'Зарегистрироваться',
  username: 'Имя пользователя',
  confirmPassword: 'Подтвердите пароль: ',
  loginHere: 'Войти здесь',
  haveAccount: 'У вас уже есть учетная запись? ',
  connectAPI: 'Подключиться к апи',
  variables: 'Переменные',
  headers: 'HTTP Заголовки',
  response: 'Запрос',
  toMain: 'На главную',
  schema: 'схему',
  openSchema: 'открыть',
  closeSchema: 'закрыть',
  apiError: 'Ошибка! Такого апи не существует или он недоступен.',
  syntaxError: 'Невалидный формат JSON',
  developer1: 'Мардон',
  developer2: 'Роман',
  developer3: 'Ольга',
  errorShema: 'Ошибка получения документации GraphQL',
  errorEmail: 'Неверный email',
  errorEmailRequired: 'Введите email',
  errorPasswordRequired: 'Введите пароль',
  errorUserRequired: 'Требуется имя пользователя',
  errorUser: 'Имя пользователя должно начинаться с заглавной буквы',
  errorPassword:
    'Пароль должен содержать не менее 8 символов, одну заглавную букву, одну строчную букву, одну цифру и один специальный символ',
  erroeMatch: 'Пароли должны совпадать',
  errorConfimPassword: 'Требуется подтверждение пароля',
  prettify: 'Выровнить',
};

export const EN_TEXT = {
  welcomeTitle: 'Dear code lovers!',
  welcomeText: `Welcome to our application! 
  We are a team of enthusiasts who put aside the stuffed turkey and gingerbread, left our loved ones to have fun under the tree and plunged into the exciting world of React.
  And here is our final project in front of you.`,
  welcomeText2: 'To get started, you need to log in ',
  welcomeText3: 'Enjoy your time!',
  login: 'Login',
  email: 'Email:',
  password: 'Password:',
  newUser: 'Don&apos;t have an account? ',
  newUserLink: 'Register here',
  logOut: 'Log out',
  registration: 'Registration',
  username: 'Username',
  confirmPassword: 'Confirm Password: ',
  loginHere: 'Login here',
  haveAccount: 'Already have an account?',
  connectAPI: 'Connect to api',
  variables: 'Variables',
  headers: 'HTTP Headers',
  response: 'Response',
  toMain: 'To main',
  schema: 'schema',
  openSchema: 'open',
  closeSchema: 'close',
  apiError: 'Error! No such API exists or is not available',
  syntaxError: 'Invalid JSON format',
  developer1: 'Mardon',
  developer2: 'Roman',
  developer3: 'Olga',
  errorShema: 'Error fetching GraphQL documentation',
  errorEmail: 'Invalid email',
  errorEmailRequired: 'Email is required',
  errorPasswordRequired: 'Password is required',
  errorUserRequired: 'Username is required',
  errorUser: 'Username must start with an uppercase letter',
  errorPassword:
    'Password must include at least 8 characters, one uppercase letter, one lowercase letter, one number, and one special character',
  erroeMatch: 'Passwords must match',
  errorConfimPassword: 'Confirm Password is required',
  prettify: 'Prettify',
};

export const FR_TEXT = {
  welcomeTitle: 'Chers amateurs de code!',
  welcomeText: `Bienvenue sur notre application! 
  Nous sommes une équipe de passionnés qui ont laissé de côté les huîtres et la bûche de Noël, laissant leurs proches s'amuser sous le sapin, et plongés à corps perdu dans l'univers passionnant de React!
  Et maintenant, notre projet final est devant vous.`,
  welcomeText2: 'Tout d’abord, vous devez vous authentifier ',
  welcomeText3: 'Profitez de votre temps!',
  login: 'Se connecter',
  email: 'Email:',
  password: 'Mot de passe:',
  newUser: "Vous n'avez pas de compte? ",
  newUserLink: 'Inscrivez-vous ici',
  logOut: 'Déconnexion',
  registration: 'Inscription',
  username: 'Username',
  confirmPassword: 'Confirmer le mot de passe:',
  loginHere: 'Connectez-vous ici',
  haveAccount: 'Vous avez déjà un compte? ',
  connectAPI: 'Connectez-vous à l’API',
  variables: 'Variables',
  headers: 'En-têtes HTTP',
  response: 'Réponse',
  toMain: 'au principal',
  schema: 'schéma',
  openSchema: 'ouvrir',
  closeSchema: 'fermer',
  apiError: "Erreur! Aucune API de ce type n'existe ou n'est pas disponible.",
  syntaxError: 'Format JSON invalide',
  developer1: 'Mardon',
  developer2: 'Roman',
  developer3: 'Olga',
  errorShema: 'Erreur lors de la récupération de la documentation GraphQL',
  errorEmail: 'E-mail invalide',
  errorEmailRequired: "L'e-mail est requis",
  errorPasswordRequired: 'Le mot de passe est requis',
  errorUserRequired: "Le nom d'utilisateur est requis",
  errorUser: "Le nom d'utilisateur doit commencer par une lettre majuscule",
  errorPassword:
    'Le mot de passe doit comprendre au moins 8 caractères, une lettre majuscule, une lettre minuscule, un chiffre et un caractère spécial',
  erroeMatch: 'Les mots de passe doivent correspondre',
  errorConfimPassword: 'Confirmer le mot de passe est requis',
  prettify: 'Embellir',
};
